### ISSUE TITLE
Error when trying to run gitfs

### ISSUE THREAD

**Issue by devomaa** [libgit2/pygit2#1018]
# Error
```python
 ✘ no@no  ~/gitfstest  gitfs [REDACTED] .
Traceback (most recent call last):
  File "/usr/bin/gitfs", line 33, in <module>
    sys.exit(load_entry_point('gitfs==0.5.1', 'console_scripts', 'gitfs')())
  File "/usr/lib/python3.8/site-packages/gitfs/__init__.py", line 19, in mount
    from gitfs.mounter import start_fuse
  File "/usr/lib/python3.8/site-packages/gitfs/mounter.py", line 22, in <module>
    from pygit2.remote import RemoteCallbacks
ImportError: cannot import name 'RemoteCallbacks' from 'pygit2.remote' (/usr/lib/python3.8/site-packages/pygit2/remote.py)

 ✘ no@no  ~/gitfstest  
```
# Additional Info:

## My uname -a output:
`Linux no 5.7.3-arch1-1 #1 SMP PREEMPT Wed, 17 Jun 2020 19:42:12 +0000 x86_64 GNU/Linux`

**Comment by omniproc** [comment]
Looks like an error in `mounter.py` from `gitfs`. `RemoteCallbacks` is not part of `pygit2.remote` but rather `pygit2.callbacks`. I guess that's because `gitfs` is using an old build of `pygit2`, see https://github.com/presslabs/gitfs/issues/323

**Comment by bqv** [comment]
Workaround?
