### ISSUE TITLE
"unsupported repository version 1"

### ISSUE THREAD

**Issue by Allen-Webb** [libgit2/pygit2#1034]
I am trying to use git-deps with a checkout that uses repository version 1 but get the following trace:

Traceback (most recent call last):
  File "/home/allenwebb/.local/bin/git-deps", line 8, in <module>
    sys.exit(run())
  File "/home/allenwebb/.local/lib/python3.8/site-packages/git_deps/cli.py", line 141, in run
    main(sys.argv[1:])
  File "/home/allenwebb/.local/lib/python3.8/site-packages/git_deps/cli.py", line 135, in main
    cli(options, args)
  File "/home/allenwebb/.local/lib/python3.8/site-packages/git_deps/cli.py", line 100, in cli
    detector = DependencyDetector(options)
  File "/home/allenwebb/.local/lib/python3.8/site-packages/git_deps/detector.py", line 31, in __init__
    self.repo = GitUtils.get_repo()
  File "/home/allenwebb/.local/lib/python3.8/site-packages/git_deps/gitutils.py", line 103, in get_repo
    return pygit2.Repository(repo_path)
  File "/home/allenwebb/.local/lib/python3.8/site-packages/pygit2/repository.py", line 1282, in __init__
    path_backend = init_file_backend(path)
_pygit2.GitError: /home/allenwebb/external/NoBackup/chromiumos/src/third_party/kernel/v5.4/.git/: unsupported repository version 1. Only versions up to 0 are supported.

**Comment by Allen-Webb** [comment]
I was able to resolve my issue by installing the top-of-tree copy of libgit2. Unfortunately, most of the distros are still using 1.0.1 or earlier.
