### ISSUE TITLE
InvalidSpecError for `repo.checkout("hash")` when `git checkout hash` works fine

### ISSUE THREAD

**Issue by AdamWill** [libgit2/pygit2#1217]
To reproduce:

git clone https://src.fedoraproject.org/rpms/python-pymongo.git
cd python-pymongo
python3
>>> import pygit2
>>> pyrepo = pygit2.Repository("./")
>>> pyrepo.checkout("a3432e746082d0c96811cbf87aa7ae8e7fe62bc8")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.11/site-packages/pygit2/repository.py", line 420, in checkout
    reference = self.lookup_reference(refname)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_pygit2.InvalidSpecError: a3432e746082d0c96811cbf87aa7ae8e7fe62bc8: the given reference name 'a3432e746082d0c96811cbf87aa7ae8e7fe62bc8' is not valid
>>> (ctrl-d)
[adamw@xps13a python-pymongo (rawhide)]$ git checkout a3432e746082d0c96811cbf87aa7ae8e7fe62bc8
Note: switching to 'a3432e746082d0c96811cbf87aa7ae8e7fe62bc8'.
[...]
HEAD is now at a3432e7 Update to 3.4.0 (#1400227).

so, checkout out that commit works fine with `git checkout` but not pygit2 `checkout`. I've no idea why not. Not sure if this is a pygit2 or libgit2 issue.

**Comment by AdamWill** [comment]
This is with pygit2 1.12.0 and libgit2 1.6.4.

**Comment by pavel-alekseev-flocktory** [comment]
https://www.pygit2.org/index_file.html#pygit2.Repository.checkout
repo.checkout() waits for reference, not a branch name,  like "refs/heads/new_branch", not just "new_branch"

**Comment by Aquarius888** [comment]
faced the same issue. Resolved using refs, like "refs/heads/branch_name", not just "branch_name"
