### ISSUE TITLE
Unable to pip install pygit2

### ISSUE THREAD

**Issue by KINFOO** [libgit2/pygit2#476]
Hi,

I just installed `gitlib2` from sources and try to `pip install --user "pygit2<0.22"`.

Unfortunately it fails. It is all ran from a __Debian stable__.

## What about `gitlib2`?

It is installed under `/home/bee/.local` at version `0.21.4`.
```bash
$ ls /home/bee/.local/lib/
libgit2.so  libgit2.so.0.21.4  libgit2.so.21  pkgconfig
```

### What is the install procedure?

```bash
$ git clone https://github.com/libgit2/libgit2.git
$ mkdir -p libgit2
$ cd libgit2/build
$ git fetch --all
$ git checkout -b v0.21.4 v0.21.4
$ export LC_CTYPE=C.UTF-8
$ cmake -DCMAKE_INSTALL_PREFIX=$LIBGIT2 ..
$ make
$ make install
```

### Is `$LIBGIT2` set?

Yes it is.
```bash
$ env | grep GIT2
LIBGIT2=/home/bee//.local
```

#### More?

```bash
$ env
LIBGIT_BUILD=/home/bee//libgit2//build
HOSTNAME=27180f82253b
TERM=xterm
LIBGIT2=/home/bee//.local
BEE_CONF=/home/bee//.bee/
LS_COLORS=rs=0 # I cut this one
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/home/bee
SHLVL=1
HOME=/home/bee/
LC_CTYPE=C.UTF-8
LIBGIT_SRC=/home/bee//libgit2/
_=/usr/bin/env
```

## A Trackeback, please

```bash
$ pip-3.2 install --user --verbose "pygit2<0.22"
Downloading/unpacking pygit2<0.22
  Ignoring link https://pypi.python.org/packages/source/p/pygit2/pygit2-0.22.0.tar.gz#md5=31dc65b3cbe6e39d75a39db86dd7cd8c (from https://pypi.python.org/simple/pygit2/), version 0.22.0 doesn't match <0.22
  Using version 0.21.4 (newest of versions: 0.21.4, 0.21.3, 0.21.2, 0.21.1, 0.21.0, 0.20.3, 0.20.2, 0.20.1, 0.20.0, 0.19.1, 0.19.0, 0.18.1, 0.18.0, 0.17.3, 0.17.2, 0.17.1, 0.17.0, 0.16.2, 0.16.1, 0.16.0)
  Running setup.py egg_info for package pygit2
    
    Installed /home/bee/build/pygit2/cffi-0.8.6-py3.2-linux-x86_64.egg
    Searching for pycparser
    Reading http://pypi.python.org/simple/pycparser/
    Best match: pycparser 2.10
    Downloading https://pypi.python.org/packages/source/p/pycparser/pycparser-2.10.tar.gz#md5=d87aed98c8a9f386aa56d365fe4d515f
    Processing pycparser-2.10.tar.gz
    Running pycparser-2.10/setup.py -q bdist_egg --dist-dir /tmp/easy_install-rvlyeq/pycparser-2.10/egg-dist-tmp-x37fzn
    zip_safe flag not set; analyzing archive contents...
    
    Installed /home/bee/build/pygit2/pycparser-2.10-py3.2.egg
    running egg_info
    creating pip-egg-info/pygit2.egg-info
    writing requirements to pip-egg-info/pygit2.egg-info/requires.txt
    writing pip-egg-info/pygit2.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/pygit2.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/pygit2.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/pygit2.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found
    
    running build_ext
    building 'pygit2_cffi_296ce50exbf062fb5' extension
    creating /home/bee/build/pygit2/pygit2/__pycache__/pygit2
    creating /home/bee/build/pygit2/pygit2/__pycache__/pygit2/__pycache__
    gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -fPIC -I/home/bee//.local/include -I/usr/include/python3.2mu -c pygit2/__pycache__/pygit2_cffi_296ce50exbf062fb5.c -o /home/bee/build/pygit2/pygit2/__pycache__/pygit2/__pycache__/pygit2_cffi_296ce50exbf062fb5.o
    gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro /home/bee/build/pygit2/pygit2/__pycache__/pygit2/__pycache__/pygit2_cffi_296ce50exbf062fb5.o -L/home/bee//.local/lib -lgit2 -o /home/bee/build/pygit2/pygit2/__pycache__/pygit2_cffi_296ce50exbf062fb5.cpython-32mu.so
    Traceback (most recent call last):
      File "/home/bee/build/pygit2/cffi-0.8.6-py3.2-linux-x86_64.egg/cffi/vengine_cpy.py", line 146, in load_library
        self.verifier.modulefilename)
    ImportError: libgit2.so.21: cannot open shared object file: No such file or directory
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/home/bee/build/pygit2/setup.py", line 202, in <module>
        cmdclass=cmdclass)
      File "/usr/lib/python3.2/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.2/distutils/dist.py", line 917, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.2/distutils/dist.py", line 936, in run_command
        cmd_obj.run()
      File "<string>", line 12, in replacement_run
      File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 254, in find_sources
        mm.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 308, in run
        self.add_defaults()
      File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 332, in add_defaults
        sdist.add_defaults(self)
      File "/usr/lib/python3/dist-packages/setuptools/command/sdist.py", line 187, in add_defaults
        build_py = self.get_finalized_command('build_py')
      File "/usr/lib/python3.2/distutils/cmd.py", line 299, in get_finalized_command
        cmd_obj.ensure_finalized()
      File "/usr/lib/python3.2/distutils/cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "/usr/lib/python3/dist-packages/setuptools/command/build_py.py", line 75, in finalize_options
        _build_py.finalize_options(self)
      File "/usr/lib/python3.2/distutils/command/build_py.py", line 45, in finalize_options
        ('force', 'force'))
      File "/usr/lib/python3.2/distutils/cmd.py", line 287, in set_undefined_options
        src_cmd_obj.ensure_finalized()
      File "/usr/lib/python3.2/distutils/cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "/home/bee/build/pygit2/setup.py", line 101, in finalize_options
        ffi, C = get_ffi()
      File "pygit2/_utils.py", line 101, in get_ffi
        include_dirs=[libgit2_include], library_dirs=[libgit2_lib])
      File "/home/bee/build/pygit2/cffi-0.8.6-py3.2-linux-x86_64.egg/cffi/api.py", line 340, in verify
        lib = self.verifier.load_library()
      File "/home/bee/build/pygit2/cffi-0.8.6-py3.2-linux-x86_64.egg/cffi/verifier.py", line 75, in load_library
        return self._load_library()
      File "/home/bee/build/pygit2/cffi-0.8.6-py3.2-linux-x86_64.egg/cffi/verifier.py", line 151, in _load_library
        return self._vengine.load_library()
      File "/home/bee/build/pygit2/cffi-0.8.6-py3.2-linux-x86_64.egg/cffi/vengine_cpy.py", line 149, in load_library
        raise ffiplatform.VerificationError(error)
    cffi.ffiplatform.VerificationError: importing '/home/bee/build/pygit2/pygit2/__pycache__/pygit2_cffi_296ce50exbf062fb5.cpython-32mu.so': libgit2.so.21: cannot open shared object file: No such file or directory
    Complete output from command python setup.py egg_info:
    

Installed /home/bee/build/pygit2/cffi-0.8.6-py3.2-linux-x86_64.egg

Searching for pycparser

Reading http://pypi.python.org/simple/pycparser/

Best match: pycparser 2.10

Downloading https://pypi.python.org/packages/source/p/pycparser/pycparser-2.10.tar.gz#md5=d87aed98c8a9f386aa56d365fe4d515f

Processing pycparser-2.10.tar.gz

Running pycparser-2.10/setup.py -q bdist_egg --dist-dir /tmp/easy_install-rvlyeq/pycparser-2.10/egg-dist-tmp-x37fzn

zip_safe flag not set; analyzing archive contents...



Installed /home/bee/build/pygit2/pycparser-2.10-py3.2.egg

running egg_info

creating pip-egg-info/pygit2.egg-info

writing requirements to pip-egg-info/pygit2.egg-info/requires.txt

writing pip-egg-info/pygit2.egg-info/PKG-INFO

writing top-level names to pip-egg-info/pygit2.egg-info/top_level.txt

writing dependency_links to pip-egg-info/pygit2.egg-info/dependency_links.txt

writing manifest file 'pip-egg-info/pygit2.egg-info/SOURCES.txt'

warning: manifest_maker: standard file '-c' not found



running build_ext

building 'pygit2_cffi_296ce50exbf062fb5' extension

creating /home/bee/build/pygit2/pygit2/__pycache__/pygit2

creating /home/bee/build/pygit2/pygit2/__pycache__/pygit2/__pycache__

gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -fPIC -I/home/bee//.local/include -I/usr/include/python3.2mu -c pygit2/__pycache__/pygit2_cffi_296ce50exbf062fb5.c -o /home/bee/build/pygit2/pygit2/__pycache__/pygit2/__pycache__/pygit2_cffi_296ce50exbf062fb5.o

gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro /home/bee/build/pygit2/pygit2/__pycache__/pygit2/__pycache__/pygit2_cffi_296ce50exbf062fb5.o -L/home/bee//.local/lib -lgit2 -o /home/bee/build/pygit2/pygit2/__pycache__/pygit2_cffi_296ce50exbf062fb5.cpython-32mu.so

Traceback (most recent call last):

  File "/home/bee/build/pygit2/cffi-0.8.6-py3.2-linux-x86_64.egg/cffi/vengine_cpy.py", line 146, in load_library

    self.verifier.modulefilename)

ImportError: libgit2.so.21: cannot open shared object file: No such file or directory



During handling of the above exception, another exception occurred:



Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/home/bee/build/pygit2/setup.py", line 202, in <module>

    cmdclass=cmdclass)

  File "/usr/lib/python3.2/distutils/core.py", line 148, in setup

    dist.run_commands()

  File "/usr/lib/python3.2/distutils/dist.py", line 917, in run_commands

    self.run_command(cmd)

  File "/usr/lib/python3.2/distutils/dist.py", line 936, in run_command

    cmd_obj.run()

  File "<string>", line 12, in replacement_run

  File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 254, in find_sources

    mm.run()

  File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 308, in run

    self.add_defaults()

  File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 332, in add_defaults

    sdist.add_defaults(self)

  File "/usr/lib/python3/dist-packages/setuptools/command/sdist.py", line 187, in add_defaults

    build_py = self.get_finalized_command('build_py')

  File "/usr/lib/python3.2/distutils/cmd.py", line 299, in get_finalized_command

    cmd_obj.ensure_finalized()

  File "/usr/lib/python3.2/distutils/cmd.py", line 107, in ensure_finalized

    self.finalize_options()

  File "/usr/lib/python3/dist-packages/setuptools/command/build_py.py", line 75, in finalize_options

    _build_py.finalize_options(self)

  File "/usr/lib/python3.2/distutils/command/build_py.py", line 45, in finalize_options

    ('force', 'force'))

  File "/usr/lib/python3.2/distutils/cmd.py", line 287, in set_undefined_options

    src_cmd_obj.ensure_finalized()

  File "/usr/lib/python3.2/distutils/cmd.py", line 107, in ensure_finalized

    self.finalize_options()

  File "/home/bee/build/pygit2/setup.py", line 101, in finalize_options

    ffi, C = get_ffi()

  File "pygit2/_utils.py", line 101, in get_ffi

    include_dirs=[libgit2_include], library_dirs=[libgit2_lib])

  File "/home/bee/build/pygit2/cffi-0.8.6-py3.2-linux-x86_64.egg/cffi/api.py", line 340, in verify

    lib = self.verifier.load_library()

  File "/home/bee/build/pygit2/cffi-0.8.6-py3.2-linux-x86_64.egg/cffi/verifier.py", line 75, in load_library

    return self._load_library()

  File "/home/bee/build/pygit2/cffi-0.8.6-py3.2-linux-x86_64.egg/cffi/verifier.py", line 151, in _load_library

    return self._vengine.load_library()

  File "/home/bee/build/pygit2/cffi-0.8.6-py3.2-linux-x86_64.egg/cffi/vengine_cpy.py", line 149, in load_library

    raise ffiplatform.VerificationError(error)

cffi.ffiplatform.VerificationError: importing '/home/bee/build/pygit2/pygit2/__pycache__/pygit2_cffi_296ce50exbf062fb5.cpython-32mu.so': libgit2.so.21: cannot open shared object file: No such file or directory

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /home/bee/build/pygit2
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 104, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 245, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 1009, in prepare_files
    req_to_install.run_egg_info()
  File "/usr/lib/python3/dist-packages/pip/req.py", line 225, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/lib/python3/dist-packages/pip/__init__.py", line 256, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command python setup.py egg_info failed with error code 1 in /home/bee/build/pygit2
```

## Expectation

How could I run successfully `pip-3.2 install --user "pygit2<0.22"`?

Thanks for the great work.
Kevin

**Comment by KINFOO** [comment]
Well, `$LD_LIBRARY_PATH` sorted the problem:
```sh
$ export LD_LIBRARY_PATH=$HOME/.local/lib
$ pip-3.2 install --user --verbose "pygit2<0.22"
```

**Comment by carlosmn** [comment]
If you install libraries to non-standard locations, you need to tell the linker where to find the shared objects. It's possible that exporting `LIBGIT2_LIB` would have worked as well, but if you want dependencies to be kept elsewhere, exporting the linker configuration would be the way to go.
