### ISSUE TITLE
Fail to build on ubuntu/trusty64 (cffi.ffiplatform.VerificationError: struct git_checkout_options: wrong total size)

### ISSUE THREAD

**Issue by keeth** [libgit2/pygit2#478]
Building on a clean ubuntu/trusty64 Vagrant image...

```
apt-get update -y
apt-get install -y python-pip git libssl-dev zlib1g-dev cmake python-dev libffi-dev libssh2-1-dev
git clone https://github.com/libgit2/libgit2 \
  && cd libgit2 \
  && mkdir build \
  && cd build \
  && cmake .. -DCMAKE_INSTALL_PREFIX=/usr \
  && cmake --build . --target install \
  && cd ../..

pip install pygit2
```

I get the following error

```
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/local/include -I/usr/include/python2.7 -c pygit2/__pycache__/pygit2_cffi_4091df83x5470904.c -o /pygit2/pygit2/__pycache__/pygit2/__pycache__/pygit2_cffi_4091df83x5470904.o
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security /pygit2/pygit2/__pycache__/pygit2/__pycache__/pygit2_cffi_4091df83x5470904.o -L/usr/local/lib -lgit2 -o /pygit2/pygit2/__pycache__/pygit2_cffi_4091df83x5470904.so
Traceback (most recent call last):
  File "setup.py", line 197, in <module>
    cmdclass=cmdclass)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 971, in run_command
    cmd_obj.ensure_finalized()
  File "/usr/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
    self.finalize_options()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 30, in finalize_options
    _install.finalize_options(self)
  File "/usr/lib/python2.7/distutils/command/install.py", line 395, in finalize_options
    ('build_lib', 'build_lib'))
  File "/usr/lib/python2.7/distutils/cmd.py", line 298, in set_undefined_options
    src_cmd_obj.ensure_finalized()
  File "/usr/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
    self.finalize_options()
  File "setup.py", line 103, in finalize_options
    ffi, C = get_ffi()
  File "pygit2/_utils.py", line 105, in get_ffi
    include_dirs=[libgit2_include], library_dirs=[libgit2_lib])
  File "/usr/local/lib/python2.7/dist-packages/cffi/api.py", line 340, in verify
    lib = self.verifier.load_library()
  File "/usr/local/lib/python2.7/dist-packages/cffi/verifier.py", line 75, in load_library
    return self._load_library()
  File "/usr/local/lib/python2.7/dist-packages/cffi/verifier.py", line 151, in _load_library
    return self._vengine.load_library()
  File "/usr/local/lib/python2.7/dist-packages/cffi/vengine_cpy.py", line 183, in load_library
    self._load(module, 'loaded', library=library)
  File "/usr/local/lib/python2.7/dist-packages/cffi/vengine_cpy.py", line 211, in _load
    method(tp, realname, module, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/cffi/vengine_cpy.py", line 431, in _loaded_cpy_struct
    self._loaded_struct_or_union(tp)
  File "/usr/local/lib/python2.7/dist-packages/cffi/vengine_cpy.py", line 534, in _loaded_struct_or_union
    check(layout[0], ffi.sizeof(BStruct), "wrong total size")
  File "/usr/local/lib/python2.7/dist-packages/cffi/vengine_cpy.py", line 530, in check
    % (msg, expectedvalue, realvalue))
cffi.ffiplatform.VerificationError: struct git_checkout_options: wrong total size (we have 120, but C compiler says 136)
```

I get the same error if I clone pygit2 and run python setup.py install.

Any ideas?

Thanks!

ps some version numbers:

```
ii  libffi-dev:amd64                 3.1~rc1+r3.0.13-12 
ii  libpython-dev:amd64         2.7.5-5ubuntu3
ii  libssl-dev:amd64               1.0.1f-1ubuntu2.8
ii  python-dev                        2.7.5-5ubuntu3
ii  python-pip                         1.5.4-1
```

**Comment by keeth** [comment]
Fixed by selecting the 0.22.0 tag on both libgit2 and pygit2.

Made a gist of the successful incantations:

https://gist.github.com/keeth/a58afe01b31f431aa878
