### ISSUE TITLE
fails to install Centos 6.5

### ISSUE THREAD

**Issue by kingoftowns** [libgit2/pygit2#511]
using libgit2 v.22.0 master:

```
Collecting pygit2
  Using cached pygit2-0.22.0.tar.gz
    compiling '_configtest.c':
    __thread int some_threadlocal_variable_42;
    Installed /tmp/pip-build-51oxmT/pygit2/cffi-0.9.2-py2.6-linux-x86_64.egg
    Searching for pycparser
    Reading http://pypi.python.org/simple/pycparser/
    Best match: pycparser 2.10
    Downloading https://pypi.python.org/packages/source/p/pycparser/pycparser-2.10.tar.gz#md5=d87aed98c8a9f386aa56d365fe4d515f
    Processing pycparser-2.10.tar.gz
    Running pycparser-2.10/setup.py -q bdist_egg --dist-dir /tmp/easy_install-lOdR8x/pycparser-2.10/egg-dist-tmp-RhY6RT
    zip_safe flag not set; analyzing archive contents...
    Installed /tmp/pip-build-51oxmT/pygit2/pycparser-2.10-py2.6.egg
    building 'pygit2_cffi_afbe5a05x5470904' extension
    gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/local/include -I/usr/include/python2.6 -c pygit2/__pycache__/pygit2_cffi_afbe5a05x5470904.c -o /tmp/pip-build-51oxmT/pygit2/pygit2/__pycache__/pygit2/__pycache__/pygit2_cffi_afbe5a05x5470904.o
    gcc -pthread -shared /tmp/pip-build-51oxmT/pygit2/pygit2/__pycache__/pygit2/__pycache__/pygit2_cffi_afbe5a05x5470904.o -L/usr/local/lib -L/usr/lib64 -lgit2 -lpython2.6 -o /tmp/pip-build-51oxmT/pygit2/pygit2/__pycache__/pygit2_cffi_afbe5a05x5470904.so
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-51oxmT/pygit2/setup.py", line 197, in <module>
        cmdclass=cmdclass)
      File "/usr/lib64/python2.6/distutils/core.py", line 152, in setup
        dist.run_commands()
      File "/usr/lib64/python2.6/distutils/dist.py", line 975, in run_commands
        self.run_command(cmd)
      File "/usr/lib64/python2.6/distutils/dist.py", line 995, in run_command
        cmd_obj.run()
      File "<string>", line 15, in replacement_run
      File "/usr/lib/python2.6/site-packages/setuptools/command/egg_info.py", line 254, in find_sources
        mm.run()
      File "/usr/lib/python2.6/site-packages/setuptools/command/egg_info.py", line 308, in run
        self.add_defaults()
      File "/usr/lib/python2.6/site-packages/setuptools/command/egg_info.py", line 332, in add_defaults
        sdist.add_defaults(self)
      File "/usr/lib/python2.6/site-packages/setuptools/command/sdist.py", line 187, in add_defaults
        build_py = self.get_finalized_command('build_py')
      File "/usr/lib64/python2.6/distutils/cmd.py", line 319, in get_finalized_command
        cmd_obj.ensure_finalized()
      File "/usr/lib64/python2.6/distutils/cmd.py", line 117, in ensure_finalized
        self.finalize_options()
      File "/usr/lib/python2.6/site-packages/setuptools/command/build_py.py", line 61, in finalize_options
        _build_py.finalize_options(self)
      File "/usr/lib64/python2.6/distutils/command/build_py.py", line 50, in finalize_options
        ('force', 'force'))
      File "/usr/lib64/python2.6/distutils/cmd.py", line 305, in set_undefined_options
        src_cmd_obj.ensure_finalized()
      File "/usr/lib64/python2.6/distutils/cmd.py", line 117, in ensure_finalized
        self.finalize_options()
      File "/tmp/pip-build-51oxmT/pygit2/setup.py", line 103, in finalize_options
        ffi, C = get_ffi()
      File "pygit2/_utils.py", line 101, in get_ffi
        include_dirs=[libgit2_include], library_dirs=[libgit2_lib])
      File "/tmp/pip-build-51oxmT/pygit2/cffi-0.9.2-py2.6-linux-x86_64.egg/cffi/api.py", line 367, in verify
        lib = self.verifier.load_library()
      File "/tmp/pip-build-51oxmT/pygit2/cffi-0.9.2-py2.6-linux-x86_64.egg/cffi/verifier.py", line 97, in load_library
        return self._load_library()
      File "/tmp/pip-build-51oxmT/pygit2/cffi-0.9.2-py2.6-linux-x86_64.egg/cffi/verifier.py", line 207, in _load_library
        return self._vengine.load_library()
      File "/tmp/pip-build-51oxmT/pygit2/cffi-0.9.2-py2.6-linux-x86_64.egg/cffi/vengine_cpy.py", line 153, in load_library
        raise ffiplatform.VerificationError(error)
    cffi.ffiplatform.VerificationError: importing '/tmp/pip-build-51oxmT/pygit2/pygit2/__pycache__/pygit2_cffi_afbe5a05x5470904.so': libgit2.so.22: cannot open shared object file: No such file or directory
```

**Comment by carlosmn** [comment]
First of all, pygit2 does not work with libgit2 master. Install one of the releases instead. As for the error message, your installation of libgit2 seems to be broken in some way. Either you are missing the shared object completely or it's in a directory which you have not told the linker to use.

**Comment by kingoftowns** [comment]
tried again with release/0.22.0, same error, the file it is complaining about installed to /usr/local/lib I added that to the PATH and got ld: cannot find -lgit2

not sure why the install would be broken, unpacked the tar, cmake ., make && make install on a clean install of centos 6.5

thanks for the help

**Comment by carlosmn** [comment]
`PATH` does not control where libraries are looked up. You might need to run `sudo ldconfig` after installing installing a new library in order for the linker to pick it up (depending on the system). "ld: cannot find -lgit2" is not the same error that you had posted.

**Comment by kingoftowns** [comment]
my bad, I missed a step, correct PATH didn't do anything, I got the cannot find -lgit2 after trying to install to a different dir.

this was resolved with:

export LD_LIBRARY_PATH=/usr/local/lib

installed fine after that, thanks for the help!!

**Comment by bradthurber** [comment]
can confirm that @kingoftowns solution of export LD_LIBRARY_PATH=/usr/local/lib works for CentOS 7 as well.
