### ISSUE TITLE
when i run sudo pip install pygit2

### ISSUE THREAD

**Issue by srinu-dipl** [libgit2/pygit2#512]
Downloading/unpacking pygit2
  Downloading pygit2-0.22.0.tar.gz (423kB): 423kB downloaded
  Running setup.py (path:/tmp/pip_build_root/pygit2/setup.py) egg_info for package pygit2

```
Installed /tmp/pip_build_root/pygit2/.eggs/cffi-0.9.2-py2.7-linux-x86_64.egg
Searching for pycparser
Reading https://pypi.python.org/simple/pycparser/
Best match: pycparser 2.10
Downloading https://pypi.python.org/packages/source/p/pycparser/pycparser-2.10.tar.gz#md5=d87aed98c8a9f386aa56d365fe4d515f
Processing pycparser-2.10.tar.gz
Writing /tmp/easy_install-oMoRn6/pycparser-2.10/setup.cfg
Running pycparser-2.10/setup.py -q bdist_egg --dist-dir /tmp/easy_install-oMoRn6/pycparser-2.10/egg-dist-tmp-qTpAQp
zip_safe flag not set; analyzing archive contents...
Moving pycparser-2.10-py2.7.egg to /tmp/pip_build_root/pygit2/.eggs

Installed /tmp/pip_build_root/pygit2/.eggs/pycparser-2.10-py2.7.egg

building 'pygit2_cffi_93ecb84x5470904' extension
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/local/include -I/usr/include/python2.7 -c pygit2/__pycache__/pygit2_cffi_93ecb84x5470904.c -o /tmp/pip_build_root/pygit2/pygit2/__pycache__/pygit2/__pycache__/pygit2_cffi_93ecb84x5470904.o
pygit2/__pycache__/pygit2_cffi_93ecb84x5470904.c:207:18: fatal error: git2.h: No such file or directory
 #include <git2.h>
                  ^
compilation terminated.
Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "/tmp/pip_build_root/pygit2/setup.py", line 197, in <module>
    cmdclass=cmdclass)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "<string>", line 15, in replacement_run
  File "build/bdist.linux-x86_64/egg/setuptools/command/egg_info.py", line 207, in find_sources
  File "build/bdist.linux-x86_64/egg/setuptools/command/egg_info.py", line 291, in run
  File "build/bdist.linux-x86_64/egg/setuptools/command/egg_info.py", line 320, in add_defaults
  File "build/bdist.linux-x86_64/egg/setuptools/command/sdist.py", line 118, in add_defaults
  File "/usr/lib/python2.7/distutils/cmd.py", line 312, in get_finalized_command
    cmd_obj.ensure_finalized()
  File "/usr/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
    self.finalize_options()
  File "build/bdist.linux-x86_64/egg/setuptools/command/build_py.py", line 28, in finalize_options
  File "/usr/lib/python2.7/distutils/command/build_py.py", line 46, in finalize_options
    ('force', 'force'))
  File "/usr/lib/python2.7/distutils/cmd.py", line 298, in set_undefined_options
    src_cmd_obj.ensure_finalized()
  File "/usr/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
    self.finalize_options()
  File "/tmp/pip_build_root/pygit2/setup.py", line 103, in finalize_options
    ffi, C = get_ffi()
  File "pygit2/_utils.py", line 101, in get_ffi
    include_dirs=[libgit2_include], library_dirs=[libgit2_lib])
  File "/tmp/pip_build_root/pygit2/.eggs/cffi-0.9.2-py2.7-linux-x86_64.egg/cffi/api.py", line 367, in verify
    lib = self.verifier.load_library()
  File "/tmp/pip_build_root/pygit2/.eggs/cffi-0.9.2-py2.7-linux-x86_64.egg/cffi/verifier.py", line 96, in load_library
    self._compile_module()
  File "/tmp/pip_build_root/pygit2/.eggs/cffi-0.9.2-py2.7-linux-x86_64.egg/cffi/verifier.py", line 192, in _compile_module
    outputfilename = ffiplatform.compile(tmpdir, self.get_extension())
  File "/tmp/pip_build_root/pygit2/.eggs/cffi-0.9.2-py2.7-linux-x86_64.egg/cffi/ffiplatform.py", line 28, in compile
    outputfilename = _build(tmpdir, ext)
  File "/tmp/pip_build_root/pygit2/.eggs/cffi-0.9.2-py2.7-linux-x86_64.egg/cffi/ffiplatform.py", line 54, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.ffiplatform.VerificationError: CompileError: command 'x86_64-linux-gnu-gcc' failed with exit status 1
Complete output from command python setup.py egg_info:
```

Installed /tmp/pip_build_root/pygit2/.eggs/cffi-0.9.2-py2.7-linux-x86_64.egg

Searching for pycparser

Reading https://pypi.python.org/simple/pycparser/

Best match: pycparser 2.10

Downloading https://pypi.python.org/packages/source/p/pycparser/pycparser-2.10.tar.gz#md5=d87aed98c8a9f386aa56d365fe4d515f

Processing pycparser-2.10.tar.gz

Writing /tmp/easy_install-oMoRn6/pycparser-2.10/setup.cfg

Running pycparser-2.10/setup.py -q bdist_egg --dist-dir /tmp/easy_install-oMoRn6/pycparser-2.10/egg-dist-tmp-qTpAQp

zip_safe flag not set; analyzing archive contents...

Moving pycparser-2.10-py2.7.egg to /tmp/pip_build_root/pygit2/.eggs

Installed /tmp/pip_build_root/pygit2/.eggs/pycparser-2.10-py2.7.egg

running egg_info

creating pip-egg-info/pygit2.egg-info

writing requirements to pip-egg-info/pygit2.egg-info/requires.txt

writing pip-egg-info/pygit2.egg-info/PKG-INFO

writing top-level names to pip-egg-info/pygit2.egg-info/top_level.txt

writing dependency_links to pip-egg-info/pygit2.egg-info/dependency_links.txt

writing manifest file 'pip-egg-info/pygit2.egg-info/SOURCES.txt'

warning: manifest_maker: standard file '-c' not found

running build_ext

building 'pygit2_cffi_93ecb84x5470904' extension

creating /tmp/pip_build_root/pygit2/pygit2/**pycache**/pygit2

creating /tmp/pip_build_root/pygit2/pygit2/**pycache**/pygit2/**pycache**

x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/local/include -I/usr/include/python2.7 -c pygit2/**pycache**/pygit2_cffi_93ecb84x5470904.c -o /tmp/pip_build_root/pygit2/pygit2/**pycache**/pygit2/**pycache**/pygit2_cffi_93ecb84x5470904.o

pygit2/**pycache**/pygit2_cffi_93ecb84x5470904.c:207:18: fatal error: git2.h: No such file or directory

 #include <git2.h>

```
              ^
```

compilation terminated.

Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/pygit2/setup.py", line 197, in <module>

```
cmdclass=cmdclass)
```

  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup

```
dist.run_commands()
```

  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands

```
self.run_command(cmd)
```

  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command

```
cmd_obj.run()
```

  File "<string>", line 15, in replacement_run

  File "build/bdist.linux-x86_64/egg/setuptools/command/egg_info.py", line 207, in find_sources

  File "build/bdist.linux-x86_64/egg/setuptools/command/egg_info.py", line 291, in run

  File "build/bdist.linux-x86_64/egg/setuptools/command/egg_info.py", line 320, in add_defaults

  File "build/bdist.linux-x86_64/egg/setuptools/command/sdist.py", line 118, in add_defaults

  File "/usr/lib/python2.7/distutils/cmd.py", line 312, in get_finalized_command

```
cmd_obj.ensure_finalized()
```

  File "/usr/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized

```
self.finalize_options()
```

  File "build/bdist.linux-x86_64/egg/setuptools/command/build_py.py", line 28, in finalize_options

  File "/usr/lib/python2.7/distutils/command/build_py.py", line 46, in finalize_options

```
('force', 'force'))
```

  File "/usr/lib/python2.7/distutils/cmd.py", line 298, in set_undefined_options

```
src_cmd_obj.ensure_finalized()
```

  File "/usr/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized

```
self.finalize_options()
```

  File "/tmp/pip_build_root/pygit2/setup.py", line 103, in finalize_options

```
ffi, C = get_ffi()
```

  File "pygit2/_utils.py", line 101, in get_ffi

```
include_dirs=[libgit2_include], library_dirs=[libgit2_lib])
```

  File "/tmp/pip_build_root/pygit2/.eggs/cffi-0.9.2-py2.7-linux-x86_64.egg/cffi/api.py", line 367, in verify

```
lib = self.verifier.load_library()
```

  File "/tmp/pip_build_root/pygit2/.eggs/cffi-0.9.2-py2.7-linux-x86_64.egg/cffi/verifier.py", line 96, in load_library

```
self._compile_module()
```

  File "/tmp/pip_build_root/pygit2/.eggs/cffi-0.9.2-py2.7-linux-x86_64.egg/cffi/verifier.py", line 192, in _compile_module

```
outputfilename = ffiplatform.compile(tmpdir, self.get_extension())
```

  File "/tmp/pip_build_root/pygit2/.eggs/cffi-0.9.2-py2.7-linux-x86_64.egg/cffi/ffiplatform.py", line 28, in compile

```
outputfilename = _build(tmpdir, ext)
```

  File "/tmp/pip_build_root/pygit2/.eggs/cffi-0.9.2-py2.7-linux-x86_64.egg/cffi/ffiplatform.py", line 54, in _build

```
raise VerificationError('%s: %s' % (e.__class__.__name__, e))
```

cffi.ffiplatform.VerificationError: CompileError: command 'x86_64-linux-gnu-gcc' failed with exit status 1

---

Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/pygit2
Storing debug log for failure in /home/administrator/.pip/pip.log

**Comment by Endle** [comment]
Same problem with you on Fedora 21 64 bit

How about install it manually?

**Comment by carlosmn** [comment]
From the error line

>pygit2/__pycache__/pygit2_cffi_93ecb84x5470904.c:207:18: fatal error: git2.h: No such file or directory

it looks like you do not have libgit2 installed.

**Comment by srinu-dipl** [comment]
ok i will check

**Comment by atmb4u** [comment]
this issue happens when I tried to install inside a virtualenv. 

This one helped: http://www.pygit2.org/install.html#libgit2-within-a-virtual-environment

**Comment by mafrosis** [comment]
For people arriving later - make sure you have package `libgit2-dev` installed

**Comment by darkpixel** [comment]
Debian 8.6, libgit2-dev is installed, ```pip install pygit2``` outputs a ton of build errors and finishes with:
```
  File "/usr/lib/python2.7/dist-packages/cffi/ffiplatform.py", line 25, in compile

    outputfilename = _build(tmpdir, ext)

  File "/usr/lib/python2.7/dist-packages/cffi/ffiplatform.py", line 51, in _build

    raise VerificationError('%s: %s' % (e.__class__.__name__, e))

cffi.ffiplatform.VerificationError: CompileError: command 'x86_64-linux-gnu-gcc' failed with exit status 1

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-nnidmR/pygit2
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 248, in main
    return command.main(cmd_args)
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 77: ordinal not in range(128)
root@salt:/etc/salt# 
```

If you need the full output, I can toss it into a gist or something.

**Comment by SentinelX101** [comment]
Pretty sure this is just related to other missing dependencies not installed by the user and can be closed. I get similar errors to @darkpixel on Debian 8.7.1 until I install these packages as well as the previously mentioned `libgit2-dev`:

`
apt install build-essential libffi-dev python-dev libgit2-dev
`

**Comment by manavkataria** [comment]
I didn't need `libgit2-dev` on my Mac OS X. `libgit2` was sufficient:
```
brew install libgit2
sudo -H pip install pygit2
```

**Comment by jdavid** [comment]
Closing, now we've manylinux wheels.

And pygit2 is nowadays available in distros, e.g. Debian 9
