### ISSUE TITLE
Error in commiting submodules

### ISSUE THREAD

**Issue by TDaglis** [libgit2/pygit2#546]
Is there a way to add a submodule to the index in order to commit?
After pulling the latest changes of my submodule, when I try to add to the index I get the following error.

```
>>> repository.index.add('mysubmodule')

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pygit2/index.py", line 205, in add
    check_error(err, True)
  File "/usr/local/lib/python2.7/dist-packages/pygit2/errors.py", line 56, in check_error
    raise GitError(message)
_pygit2.GitError: Failed to read file into stream: Is a directory
```

If working with submodules is not possible at the moment, would it be possible to somehow ignore submodule changes in `add_all` since it raises the same error and cannot be used anymore?

```
>>> repository.index.add_all()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pygit2/index.py", line 180, in add_all
    check_error(err, True)
  File "/usr/local/lib/python2.7/dist-packages/pygit2/errors.py", line 56, in check_error
    raise GitError(message)
_pygit2.GitError: Failed to read file into stream: Is a directory
```

**Comment by carlosmn** [comment]
There is a fix waiting to be backported to the maintenance branch in libgit2. You can cherry-pick it yourself or wait for the release for `add_all()` to work. Otherwise, you'd have to perform the diff and adds yourself.

**Comment by TDaglis** [comment]
Thanks :+1: 
I'll check out the fix.
