### ISSUE TITLE
pygit2 (Ver 0.22.0) /usr/bin/ld: cannot find -lgit2

### ISSUE THREAD

**Issue by santublr** [libgit2/pygit2#555]
Hello,

Trying to install pygit2 on RHEL 6.4, Python 3.3.2. Libgit2 0.22.0 installation went fine but the libraries the include files are installed in a seperate path. 

When Importing the pygit2 the import fails with ld error.

Type "help", "copyright", "credits" or "license" for more information.
>>> import pygit2
/usr/bin/ld: cannot find -lgit2
collect2: ld returned 1 exit status
Traceback (most recent call last):
  File "/opt/perforce/demo_setup/git-fusion/libexec/lib/python3.3/distutils/unixccompiler.py", line 194, in link
    self.spawn(linker + ld_args)
  File "/opt/perforce/demo_setup/git-fusion/libexec/lib/python3.3/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/opt/perforce/demo_setup/git-fusion/libexec/lib/python3.3/distutils/spawn.py", line 32, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/opt/perforce/demo_setup/git-fusion/libexec/lib/python3.3/distutils/spawn.py", line 163, in _spawn_posix
    % (cmd[0], exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Thx,
Santosh

**Comment by carlosmn** [comment]
If you're installing into a different path from the one where the system is looking, you need to take extra steps. See the [install instructions](http://www.pygit2.org/install.html#libgit2-within-a-virtual-environment)

**Comment by santublr** [comment]
Yes, following the instructions did worked. 

Thanks for your support.
