### ISSUE TITLE
Test test.test_refs.ReferencesTest is failing when timezone is not UTC

### ISSUE THREAD

**Issue by onovy** [libgit2/pygit2#626]
```
TZ="/usr/share/zoneinfo/Etc/GMT-14" python2.7 setup.py test -v

...
FAIL: test_set_target_with_message (test.test_refs.ReferencesTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/test/test_refs.py", line 122, in test_set_target_with_message
    self.assertEqualSignature(list(reference.log())[0].committer, sig)
  File "/<<PKGBUILDDIR>>/test/utils.py", line 124, in assertEqualSignature
    self.assertEqual(a.offset, b.offset)
AssertionError: 0 != 840

**Comment by carlosmn** [comment]
Both of the sources of time data are the same function, so it's really odd that it would behave this way. The issue however isn't that it's set to not-UTC, but the particular timezone you're using there. Using other files from within `/usr/share/zoneinfo/Etc/` do work.

**Comment by carlosmn** [comment]
The behaviour is even stranger since passing in a file from that directory seems to reverse the direction of the time shift. Using `GMT+1` causes an offset of `-60` even though it should be `60`. It seems these files/form makes libc confused about where GMT is.
