### ISSUE TITLE
Configuring pygit2==0.20.3 and libgit2==0.20.0 on Debian

### ISSUE THREAD

**Issue by mo-mughrabi** [libgit2/pygit2#635]
I've been trying to build a docker file to install salt with pygit2 and libgit2 using a debian:jessie release.

It seems like everything passes successfully, but when try to import `pygit2` its failing

P.S I specifically require verion `.0.20.0` for libgit2 and `0.20.3` for pygit2 for saltstack API to work as its not compatible with more recent releases 

``` python
>>> import pygit2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pygit2/__init__.py", line 32, in <module>
    import _pygit2
ImportError: /usr/local/lib/python2.7/dist-packages/_pygit2.so: undefined symbol: git_note_oid
```

Below is my docker file, 

``` Dockerfile
FROM debian:jessie

# Install packages
ADD http://debian.saltstack.com/debian-salt-team-joehealy.gpg.key /tmp/debian-salt-team-joehealy.gpg.key
RUN echo "deb http://debian.saltstack.com/debian jessie-saltstack main" | tee /etc/apt/sources.list.d/saltstack.list && \
    apt-key add /tmp/debian-salt-team-joehealy.gpg.key && \
    DEBIAN_FRONTEND=noninteractive apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -yqq \
    salt-master \
    salt-minion \
    salt-cloud \
    salt-api \
    salt-ssh \
    salt-syndic \
    cmake \
    gcc \
    pkg-config \
    libssh2-1-dev \
    libssl-dev \
    libffi-dev \
    python-dev \
    python-pip \
    build-essential \
    git \
    python-setuptools \
    libgit2-dev \
    zlib1g \
    libssl1.0.0 \
    libhttp-parser-dev \
    libc6 \
    ca-certificates

RUN cd /tmp && \
    wget https://github.com/openssl/openssl/archive/OpenSSL_1_0_1r.tar.gz && \
    tar xzf OpenSSL_1_0_1r.tar.gz && \
    cd openssl-OpenSSL_1_0_1r && \
    ./config -fPIC --prefix=/usr -ldl && \
    make && \
    make install

RUN cd /tmp && \
    wget https://github.com/libgit2/libgit2/archive/v0.20.0.tar.gz && \
    tar xzf v0.20.0.tar.gz && \
    cd libgit2-0.20.0/

RUN cd /tmp/libgit2-0.20.0 && \
    cmake -DCMAKE_INSTALL_PREFIX=/usr && \
    cmake --build . --target install && \
    ldconfig

RUN pip install pip==8.1.2 && \
    pip install --upgrade cffi && \
    pip install -I pygit2==0.20.0 && \
    pip install cherrypy==3.2.2 \
                tornado==4.3 \
                docker-py==1.8.1 \
                halite==0.1.17 \
                GitPython==0.3.2.RC1 \
                pyOpenSSL==0.15.1
# Ports
EXPOSE 4505 4506

# Run Command
CMD "salt-master"

```

Can someone please advise?

**Comment by mo-mughrabi** [comment]
Hmm I tried to upgrade to a recent version though but still cannot import `pygit`, but with different message 

```
>>> import pygit2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pygit2/__init__.py", line 32, in <module>
    from _pygit2 import *
ImportError: /usr/local/lib/python2.7/dist-packages/_pygit2.so: undefined symbol: git_treebuilder_new
```

Used same dockerfile from above, except changed version of libgit2 to use `0.24.0` and pygit2 to use `0.24.0`

**Comment by carlosmn** [comment]
These error messages look like you're loading a different libgit2 from what you're building against. `ldd`  on the pygit2 shared object should show you what the linker would be trying to load.

**Comment by jdavid** [comment]
Closing, pygit2 is packaged in Debian now, since stretch.
