### ISSUE TITLE
Intermittent exception: 'NoneType' object has no attribute 'git_index_free'

### ISSUE THREAD

**Issue by yan12125** [libgit2/pygit2#649]
About one in ten my script raises the following exception:

```
Exception ignored in: <bound method Remote.__del__ of <pygit2.remote.Remote object at 0x7ff050e8b908>>
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/pygit2/remote.py", line 334, in __del__
AttributeError: 'NoneType' object has no attribute 'git_remote_free'
Exception ignored in: <bound method Index.__del__ of <pygit2.index.Index object at 0x7ff0568dd898>>
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/pygit2/index.py", line 69, in __del__
AttributeError: 'NoneType' object has no attribute 'git_index_free'
```

I haven't found a good way to reproduce it.

My script is at: https://github.com/yan12125/aur/blob/master/scripts/local_to_remote.py

**Comment by yan12125** [comment]
Haven't see this issue for a long time. I guess it has been fixed somewhere.
