### ISSUE TITLE
Installation fails - missing libffi, don't know why?

### ISSUE THREAD

**Issue by qwertystop** [libgit2/pygit2#675]
I was able to install libgit2 following the instructions [here](http://www.pygit2.org/install.html). Then following the instructions for pygit2:
```
qwertystop  ~  pip install pygit2
Collecting pygit2
  Using cached pygit2-0.24.2.tar.gz
    Complete output from command python setup.py egg_info:
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory
    compilation terminated.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-GgFuXC/pygit2/setup.py", line 210, in <module>
        **extra_args)
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 269, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 313, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 826, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1092, in best_match
        return self.obtain(req, installer)
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1104, in obtain
        return installer(requirement)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 380, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 663, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 693, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 873, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1101, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1089, in run_setup
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-GgFuXC/pygit2/
```
I have no idea where `libffi.pc` might be. Attempting `sudo find / -name libffi.pc` finds nothing.

OS is Linux Mint 18.

**Comment by dieter-ve** [comment]
Working on debian here.
Simply had to install the package libffi-dev

hope it helps,
Dieter

**Comment by qwertystop** [comment]
Installed libffi-dev with apt. Seemed to work.

Retried `sudo pip install`. Different error from before, at least:

```
Collecting pygit2
  Using cached pygit2-0.24.2.tar.gz
Requirement already satisfied: cffi in /usr/local/lib/python3.5/dist-packages (from pygit2)
Requirement already satisfied: six in ./.local/lib/python3.5/site-packages (from pygit2)
Requirement already satisfied: pycparser in /usr/local/lib/python3.5/dist-packages (from cffi->pygit2)
Building wheels for collected packages: pygit2
  Running setup.py bdist_wheel for pygit2: started
  Running setup.py bdist_wheel for pygit2: finished with status 'error'
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-413rfvd8/pygit2/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpn340mxjypip-wheel- --python-tag cp35:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.5
  creating build/lib.linux-x86_64-3.5/pygit2
  copying pygit2/__init__.py -> build/lib.linux-x86_64-3.5/pygit2
  copying pygit2/repository.py -> build/lib.linux-x86_64-3.5/pygit2
  copying pygit2/errors.py -> build/lib.linux-x86_64-3.5/pygit2
  copying pygit2/utils.py -> build/lib.linux-x86_64-3.5/pygit2
  copying pygit2/py3.py -> build/lib.linux-x86_64-3.5/pygit2
  copying pygit2/credentials.py -> build/lib.linux-x86_64-3.5/pygit2
  copying pygit2/refspec.py -> build/lib.linux-x86_64-3.5/pygit2
  copying pygit2/submodule.py -> build/lib.linux-x86_64-3.5/pygit2
  copying pygit2/remote.py -> build/lib.linux-x86_64-3.5/pygit2
  copying pygit2/_build.py -> build/lib.linux-x86_64-3.5/pygit2
  copying pygit2/py2.py -> build/lib.linux-x86_64-3.5/pygit2
  copying pygit2/ffi.py -> build/lib.linux-x86_64-3.5/pygit2
  copying pygit2/config.py -> build/lib.linux-x86_64-3.5/pygit2
  copying pygit2/index.py -> build/lib.linux-x86_64-3.5/pygit2
  copying pygit2/_run.py -> build/lib.linux-x86_64-3.5/pygit2
  copying pygit2/settings.py -> build/lib.linux-x86_64-3.5/pygit2
  copying pygit2/blame.py -> build/lib.linux-x86_64-3.5/pygit2
  copying pygit2/decl.h -> build/lib.linux-x86_64-3.5/pygit2
  running build_ext
  generating cffi module 'build/temp.linux-x86_64-3.5/pygit2._libgit2.c'
  creating build/temp.linux-x86_64-3.5
  building '_pygit2' extension
  creating build/temp.linux-x86_64-3.5/src
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/local/include -I/usr/include/python3.5m -c src/blob.c -o build/temp.linux-x86_64-3.5/src/blob.o
  In file included from src/blob.c:30:0:
  src/blob.h:33:18: fatal error: git2.h: No such file or directory
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Running setup.py clean for pygit2
Failed to build pygit2
Installing collected packages: pygit2
  Running setup.py install for pygit2: started
    Running setup.py install for pygit2: finished with status 'error'
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-413rfvd8/pygit2/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-w9n33fax-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.5
    creating build/lib.linux-x86_64-3.5/pygit2
    copying pygit2/__init__.py -> build/lib.linux-x86_64-3.5/pygit2
    copying pygit2/repository.py -> build/lib.linux-x86_64-3.5/pygit2
    copying pygit2/errors.py -> build/lib.linux-x86_64-3.5/pygit2
    copying pygit2/utils.py -> build/lib.linux-x86_64-3.5/pygit2
    copying pygit2/py3.py -> build/lib.linux-x86_64-3.5/pygit2
    copying pygit2/credentials.py -> build/lib.linux-x86_64-3.5/pygit2
    copying pygit2/refspec.py -> build/lib.linux-x86_64-3.5/pygit2
    copying pygit2/submodule.py -> build/lib.linux-x86_64-3.5/pygit2
    copying pygit2/remote.py -> build/lib.linux-x86_64-3.5/pygit2
    copying pygit2/_build.py -> build/lib.linux-x86_64-3.5/pygit2
    copying pygit2/py2.py -> build/lib.linux-x86_64-3.5/pygit2
    copying pygit2/ffi.py -> build/lib.linux-x86_64-3.5/pygit2
    copying pygit2/config.py -> build/lib.linux-x86_64-3.5/pygit2
    copying pygit2/index.py -> build/lib.linux-x86_64-3.5/pygit2
    copying pygit2/_run.py -> build/lib.linux-x86_64-3.5/pygit2
    copying pygit2/settings.py -> build/lib.linux-x86_64-3.5/pygit2
    copying pygit2/blame.py -> build/lib.linux-x86_64-3.5/pygit2
    copying pygit2/decl.h -> build/lib.linux-x86_64-3.5/pygit2
    running build_ext
    generating cffi module 'build/temp.linux-x86_64-3.5/pygit2._libgit2.c'
    creating build/temp.linux-x86_64-3.5
    building '_pygit2' extension
    creating build/temp.linux-x86_64-3.5/src
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/local/include -I/usr/include/python3.5m -c src/blob.c -o build/temp.linux-x86_64-3.5/src/blob.o
    In file included from src/blob.c:30:0:
    src/blob.h:33:18: fatal error: git2.h: No such file or directory
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------

```

**Comment by carlosmn** [comment]
pygit2 needs libgit2 installed. Install libgit2 v0.24.x to your system and then it will be able to find the library.

**Comment by peteristhegreat** [comment]
GitPython is a useful alternative when in a pinch that doesn't require libgit2.
