### ISSUE TITLE
pygit2 installation error. 

### ISSUE THREAD

**Issue by santublr** [libgit2/pygit2#729]
This issue which I'm reporting may be repetative one, but after googling and trying all the options I'm still not able to load the right pygit2.

pygit2 version 0.22.0
libgit2 version 0.22.0
pycparse version 2.18
cffi version 0.9.2
Python Version 3.3.2
OS CentOS release 6.8 (Fina

python3.3 -c 'import pygit2'
Traceback (most recent call last):
  File "/scm/apps/Python-3.3.2/lib/python3.3/site-packages/cffi-0.9.2-py3.3-linux-x86_64.egg/cffi/api.py", line 147, in _typeof
    result = self._parsed_types[cdecl]
KeyError: 'int (*git_repository_create_cb)(git_repository **out,const char *path, int bare, void *payload)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scm/apps/Python-3.3.2/lib/python3.3/site-packages/cffi-0.9.2-py3.3-linux-x86_64.egg/cffi/cparser.py", line 126, in _parse
    ast = _get_parser().parse(csource)
  File "/scm/apps/Python-3.3.2/lib/python3.3/site-packages/pycparser-2.18-py3.3.egg/pycparser/c_parser.py", line 152, in parse
    debug=debuglevel)
  File "/scm/apps/Python-3.3.2/lib/python3.3/site-packages/pycparser-2.18-py3.3.egg/pycparser/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/scm/apps/Python-3.3.2/lib/python3.3/site-packages/pycparser-2.18-py3.3.egg/pycparser/ply/yacc.py", line 1199, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/scm/apps/Python-3.3.2/lib/python3.3/site-packages/pycparser-2.18-py3.3.egg/pycparser/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "/scm/apps/Python-3.3.2/lib/python3.3/site-packages/pycparser-2.18-py3.3.egg/pycparser/c_parser.py", line 1761, in p_error
    column=self.clex.find_tok_column(p)))
  File "/scm/apps/Python-3.3.2/lib/python3.3/site-packages/pycparser-2.18-py3.3.egg/pycparser/plyparser.py", line 66, in _parse_error
    raise ParseError("%s: %s" % (coord, msg))
pycparser.plyparser.ParseError: :71:7: before: git_repository_create_cb

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/scm/apps/Python-3.3.2/lib/python3.3/site-packages/pygit2-0.22.0-py3.3-linux-x86_64.egg/pygit2/__init__.py", line 134, in <module>
    @ffi.callback('int (*git_repository_create_cb)(git_repository **out,'
  File "/scm/apps/Python-3.3.2/lib/python3.3/site-packages/cffi-0.9.2-py3.3-linux-x86_64.egg/cffi/api.py", line 297, in callback
    cdecl = self._typeof(cdecl, consider_function_as_funcptr=True)
  File "/scm/apps/Python-3.3.2/lib/python3.3/site-packages/cffi-0.9.2-py3.3-linux-x86_64.egg/cffi/api.py", line 150, in _typeof
    result = self._typeof_locked(cdecl)
  File "/scm/apps/Python-3.3.2/lib/python3.3/site-packages/cffi-0.9.2-py3.3-linux-x86_64.egg/cffi/api.py", line 135, in _typeof_locked
    type = self._parser.parse_type(cdecl)
  File "/scm/apps/Python-3.3.2/lib/python3.3/site-packages/cffi-0.9.2-py3.3-linux-x86_64.egg/cffi/cparser.py", line 275, in parse_type
    ast, macros = self._parse('void __dummy(\n%s\n);' % cdecl)[:2]
  File "/scm/apps/Python-3.3.2/lib/python3.3/site-packages/cffi-0.9.2-py3.3-linux-x86_64.egg/cffi/cparser.py", line 128, in _parse
    self.convert_pycparser_error(e, csource)
  File "/scm/apps/Python-3.3.2/lib/python3.3/site-packages/cffi-0.9.2-py3.3-linux-x86_64.egg/cffi/cparser.py", line 157, in convert_pycparser_error
    raise api.CDefError(msg)
cffi.api.CDefError: cannot parse "int (*git_repository_create_cb)(git_repository **out,const char *path, int bare, void *payload)"
:71:7: before: git_repository_create_cb
root@sc-p4-gitfusion-2017:/scm/p4/bin.gitfusion/2017.1 # export LD_LIBRARY_PATH=$LIBGIT2/lib
root@sc-p4-gitfusion-2017:/scm/p4/bin.gitfusion/2017.1 # export LIBGIT2=/usr/local
root@sc-p4-gitfusion-2017:/scm/p4/bin.gitfusion/2017.1 # python -c 'import pygit2'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named pygit2
root@sc-p4-gitfusion-2017:/scm/p4/bin.gitfusion/2017.1 # python3.3 -c 'import pygit2'
Traceback (most recent call last):
  File "/scm/apps/Python-3.3.2/lib/python3.3/site-packages/cffi-0.9.2-py3.3-linux-x86_64.egg/cffi/api.py", line 147, in _typeof
    result = self._parsed_types[cdecl]
KeyError: 'int (*git_repository_create_cb)(git_repository **out,const char *path, int bare, void *payload)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scm/apps/Python-3.3.2/lib/python3.3/site-packages/cffi-0.9.2-py3.3-linux-x86_64.egg/cffi/cparser.py", line 126, in _parse
    ast = _get_parser().parse(csource)
  File "/scm/apps/Python-3.3.2/lib/python3.3/site-packages/pycparser-2.18-py3.3.egg/pycparser/c_parser.py", line 152, in parse
    debug=debuglevel)
  File "/scm/apps/Python-3.3.2/lib/python3.3/site-packages/pycparser-2.18-py3.3.egg/pycparser/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/scm/apps/Python-3.3.2/lib/python3.3/site-packages/pycparser-2.18-py3.3.egg/pycparser/ply/yacc.py", line 1199, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/scm/apps/Python-3.3.2/lib/python3.3/site-packages/pycparser-2.18-py3.3.egg/pycparser/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "/scm/apps/Python-3.3.2/lib/python3.3/site-packages/pycparser-2.18-py3.3.egg/pycparser/c_parser.py", line 1761, in p_error
    column=self.clex.find_tok_column(p)))
  File "/scm/apps/Python-3.3.2/lib/python3.3/site-packages/pycparser-2.18-py3.3.egg/pycparser/plyparser.py", line 66, in _parse_error
    raise ParseError("%s: %s" % (coord, msg))
pycparser.plyparser.ParseError: :71:7: before: git_repository_create_cb

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/scm/apps/Python-3.3.2/lib/python3.3/site-packages/pygit2-0.22.0-py3.3-linux-x86_64.egg/pygit2/__init__.py", line 134, in <module>
    @ffi.callback('int (*git_repository_create_cb)(git_repository **out,'
  File "/scm/apps/Python-3.3.2/lib/python3.3/site-packages/cffi-0.9.2-py3.3-linux-x86_64.egg/cffi/api.py", line 297, in callback
    cdecl = self._typeof(cdecl, consider_function_as_funcptr=True)
  File "/scm/apps/Python-3.3.2/lib/python3.3/site-packages/cffi-0.9.2-py3.3-linux-x86_64.egg/cffi/api.py", line 150, in _typeof
    result = self._typeof_locked(cdecl)
  File "/scm/apps/Python-3.3.2/lib/python3.3/site-packages/cffi-0.9.2-py3.3-linux-x86_64.egg/cffi/api.py", line 135, in _typeof_locked
    type = self._parser.parse_type(cdecl)
  File "/scm/apps/Python-3.3.2/lib/python3.3/site-packages/cffi-0.9.2-py3.3-linux-x86_64.egg/cffi/cparser.py", line 275, in parse_type
    ast, macros = self._parse('void __dummy(\n%s\n);' % cdecl)[:2]
  File "/scm/apps/Python-3.3.2/lib/python3.3/site-packages/cffi-0.9.2-py3.3-linux-x86_64.egg/cffi/cparser.py", line 128, in _parse
    self.convert_pycparser_error(e, csource)
  File "/scm/apps/Python-3.3.2/lib/python3.3/site-packages/cffi-0.9.2-py3.3-linux-x86_64.egg/cffi/cparser.py", line 157, in convert_pycparser_error
    raise api.CDefError(msg)
cffi.api.CDefError: cannot parse "int (*git_repository_create_cb)(git_repository **out,const char *path, int bare, void *payload)"
:71:7: before: git_repository_create_cb

**Comment by jdavid** [comment]
Are these packages from the CentOS distribution? 0.22 is quite old, I would recommend to use the latest version; install libgit2 0.26 manually if not available in the distribution, then install pygit2 with pip, maybe in a virtual environment.

**Comment by deadalus-wings** [comment]
failed with error code 1 in /tmp/pip-build-4gA9EO/pygit2/
 i tried installing this library and keep getting this error
full error:
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-4gA9EO/pygit2/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-QR0q4I-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-4gA9EO/pygit2/

how do i fix this ?

**Comment by jdavid** [comment]
Closing, pycparser 2.18 and 2.19 are known to be broken, see issue #846 

Now in setup.py we require a version older than 2.18
