### ISSUE TITLE
pygit2 verification step error

### ISSUE THREAD

**Issue by kubilay-eren** [libgit2/pygit2#780]
" kubilay@kubilay-Inspiron-5521:~$ python -c 'import pygit2'
Traceback (most recent call last):
  File `"<string>",` line 1, in `<module>`
ImportError: No module named pygit2 "

How can I fix the above error?

**Comment by jdavid** [comment]
It looks like pygit2 is *not* installed. Install docs are here, http://www.pygit2.org/install.html

**Comment by kubilay-eren** [comment]
Yes you are right pygit2 is not installed. I get an error while trying to load by looking at the documents.
The error is;


"    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    c/_cffi_backend.c:15:17: fatal error: ffi.h: Böyle bir dosya ya da dizin yok
    compilation terminated.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-oECYkS/pygit2/setup.py", line 202, in <module>
        **extra_args)
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 269, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 313, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 826, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1092, in best_match
        return self.obtain(req, installer)
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1104, in obtain
        return installer(requirement)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 380, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 663, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 693, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 873, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1101, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1089, in run_setup
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-oECYkS/pygit2/
 "

**Comment by pypingou** [comment]
Since you seem to be using linux, did you check your distribution's packages? May be just as easy to yum/dnf/apt-get/emerge it

**Comment by jdavid** [comment]
yes, try the distribution package

otherwise the message error tells what's missing:

    No package 'libffi' found

What distribution do you use?

**Comment by 98bahanurkadirhan** [comment]
Bunlar ne anlamadim da

23 Mar 2018 Cum 11:26 tarihinde J. David Ibáñez <notifications@github.com>
şunu yazdı:

**Comment by kubilay-eren** [comment]
Ubutu 16.04.4 Ich verwende LTS \ n \ l-Verteilung.

**Comment by jdavid** [comment]
Then just ``apt-get install python3-pygit2`` or ``apt-get install python-pygit2``, you will get the 0.24 version.

**Comment by jdavid** [comment]
Closing, now we have manylinux wheels, so it will be easier to install.
