### ISSUE TITLE
TypeError: don't know how to make test from: <CompiledFFI object at 0x7f43c00693e8>

### ISSUE THREAD

**Issue by ignatenkobrain** [libgit2/pygit2#868]
```
+ /usr/bin/python3 setup.py test
running test
running egg_info
writing pygit2.egg-info/PKG-INFO
writing dependency_links to pygit2.egg-info/dependency_links.txt
writing requirements to pygit2.egg-info/requires.txt
writing top-level names to pygit2.egg-info/top_level.txt
reading manifest file 'pygit2.egg-info/SOURCES.txt'
writing manifest file 'pygit2.egg-info/SOURCES.txt'
running build_ext
generating cffi module 'build/temp.linux-x86_64-3.6/pygit2._libgit2.c'
already up-to-date
copying build/lib.linux-x86_64-3.6/_pygit2.cpython-36m-x86_64-linux-gnu.so -> 
copying build/lib.linux-x86_64-3.6/pygit2/_libgit2.abi3.so -> pygit2
BUILDSTDERR: Traceback (most recent call last):
BUILDSTDERR:   File "setup.py", line 160, in <module>
BUILDSTDERR:     **extra_args)
BUILDSTDERR:   File "/usr/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
BUILDSTDERR:     return distutils.core.setup(**attrs)
BUILDSTDERR:   File "/usr/lib64/python3.6/distutils/core.py", line 148, in setup
BUILDSTDERR:     dist.run_commands()
BUILDSTDERR:   File "/usr/lib64/python3.6/distutils/dist.py", line 955, in run_commands
BUILDSTDERR:     self.run_command(cmd)
BUILDSTDERR:   File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
BUILDSTDERR:     cmd_obj.run()
BUILDSTDERR:   File "/usr/lib/python3.6/site-packages/setuptools/command/test.py", line 226, in run
BUILDSTDERR:     self.run_tests()
BUILDSTDERR:   File "/usr/lib/python3.6/site-packages/setuptools/command/test.py", line 248, in run_tests
BUILDSTDERR:     exit=False,
BUILDSTDERR:   File "/usr/lib64/python3.6/unittest/main.py", line 94, in __init__
BUILDSTDERR:     self.parseArgs(argv)
BUILDSTDERR:   File "/usr/lib64/python3.6/unittest/main.py", line 118, in parseArgs
BUILDSTDERR:     self._do_discovery(argv[2:])
BUILDSTDERR:   File "/usr/lib64/python3.6/unittest/main.py", line 229, in _do_discovery
BUILDSTDERR:     self.test = loader.discover(self.start, self.pattern, self.top)
BUILDSTDERR:   File "/usr/lib64/python3.6/unittest/loader.py", line 341, in discover
BUILDSTDERR:     tests = list(self._find_tests(start_dir, pattern))
BUILDSTDERR:   File "/usr/lib64/python3.6/unittest/loader.py", line 398, in _find_tests
BUILDSTDERR:     full_path, pattern, namespace)
BUILDSTDERR:   File "/usr/lib64/python3.6/unittest/loader.py", line 475, in _find_test_path
BUILDSTDERR:     tests = self.loadTestsFromModule(package, pattern=pattern)
BUILDSTDERR:   File "/usr/lib/python3.6/site-packages/setuptools/command/test.py", line 52, in loadTestsFromModule
BUILDSTDERR:     tests.append(self.loadTestsFromName(submodule))
BUILDSTDERR:   File "/usr/lib64/python3.6/unittest/loader.py", line 213, in loadTestsFromName
BUILDSTDERR:     raise TypeError("don't know how to make test from: %s" % obj)
BUILDSTDERR: TypeError: don't know how to make test from: <CompiledFFI object at 0x7f43c00693e8>
RPM build errors:
BUILDSTDERR: error: Bad exit status from /var/tmp/rpm-tmp.DMl5y5 (%check)
BUILDSTDERR:     Bad exit status from /var/tmp/rpm-tmp.DMl5y5 (%check)
```

This happens with latest released pygit2 when I'm trying to package it for Fedora.

**Comment by jdavid** [comment]
We're using `pytest` now.

**Comment by webknjaz** [comment]
@ignatenkobrain you can check out configs of Travis CI and AppVeyor CI to get an idea of how to run tests...

P.S. https://github.com/libgit2/pygit2/pull/869 is going to produce manylinux1 wheels, maybe you could reuse that...

**Comment by ignatenkobrain** [comment]
We need to build everything from source.

When switching to py-test directly, error disappears.. Thanks!

**Comment by webknjaz** [comment]
@ignatenkobrain I meant that you could probably reuse scripts involved in building the dist...
