### ISSUE TITLE
GitError: failed to stat '/opt/webapp/projects/project-2-project-anonymous/.git'

### ISSUE THREAD

**Issue by inf3cti0n95** [libgit2/pygit2#881]
Enviroment -
Docker - Alpine with minconda3

It show error GitError: failed to stat '/opt/webapp/projects/project-2-project-anonymous/.git'

```
Traceback (most recent call last):
  File "/opt/conda/envs/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/opt/conda/envs/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/conda/envs/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/conda/envs/venv/lib/python3.7/site-packages/django/contrib/admin/options.py", line 604, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/opt/conda/envs/venv/lib/python3.7/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/opt/conda/envs/venv/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/opt/conda/envs/venv/lib/python3.7/site-packages/django/contrib/admin/sites.py", line 223, in inner
    return view(request, *args, **kwargs)
  File "/opt/conda/envs/venv/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1637, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/opt/conda/envs/venv/lib/python3.7/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/opt/conda/envs/venv/lib/python3.7/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/opt/conda/envs/venv/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1525, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/opt/conda/envs/venv/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1564, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "/opt/conda/envs/venv/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1091, in save_model
    obj.save()
  File "/opt/conda/envs/venv/lib/python3.7/site-packages/django/db/models/base.py", line 718, in save
    force_update=force_update, update_fields=update_fields)
  File "/opt/conda/envs/venv/lib/python3.7/site-packages/django/db/models/base.py", line 758, in save_base
    update_fields=update_fields, raw=raw, using=using,
  File "/opt/conda/envs/venv/lib/python3.7/site-packages/django/dispatch/dispatcher.py", line 175, in send
    for receiver in self._live_receivers(sender)
  File "/opt/conda/envs/venv/lib/python3.7/site-packages/django/dispatch/dispatcher.py", line 175, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "/opt/webapp/licensing_service/project/models.py", line 70, in post_save_handler
    instance.source.clone_repository(repository_url=instance.source_url)
  File "/opt/webapp/licensing_service/project/fields.py", line 37, in clone_repository
    pygit2.clone_repository(repository_url, self.source_directory, bare=False)
  File "/opt/conda/envs/venv/lib/python3.7/site-packages/pygit2/__init__.py", line 265, in clone_repository
    check_error(err)
  File "/opt/conda/envs/venv/lib/python3.7/site-packages/pygit2/errors.py", line 64, in check_error
    raise GitError(message)
_pygit2.GitError: failed to stat '/opt/webapp/projects/project-2-project-anonymous/.git': 
```

**Comment by webknjaz** [comment]
What are the versions of libgit2 and pygit2?

**Comment by webknjaz** [comment]
Best guess is that `failed to stat` is probably referring to the non-existing file/folder in the file system.

**Comment by imbuedHope** [comment]
Does the folder already exist when you call `pygit2.clone_repository`?

**Comment by webknjaz** [comment]
Does your process have sufficient privileges to create it?

**Comment by inf3cti0n95** [comment]
@imbuedHope @webknjaz I dont know why it was not working, I have moved to custom git solution. Sorry. I also thought of the above reasons. But, there seemed to be some other issue. I don't know.
