### ISSUE TITLE
What is the "ptr" referencing in push function?

### ISSUE THREAD

**Issue by mrkcmo** [libgit2/pygit2#912]
I am trying to do a git push of a new branch and the function for push requires refspecs and ptr. What is the "ptr" referencing? I don't see any sort of description in the documentation. 

```
Exception ignored in: <bound method Remote.__del__ of <pygit2.remote.Remote object at 0x0000024E6DE8B5C0>>
Traceback (most recent call last):
  File "C:\Users\chfortne\AppData\Local\Programs\Python\Python36\lib\site-packages\pygit2\remote.py", line 355, in __del__
    C.git_remote_free(self._remote)
AttributeError: 'Remote' object has no attribute '_remote'
Traceback (most recent call last):
  File "create.py", line 99, in <module>
    repository_push(repo, short_name)
  File "create.py", line 93, in repository_push
    remote = Remote('./.git')
TypeError: __init__() missing 1 required positional argument: 'ptr'
```

**Comment by jdavid** [comment]
Hi, could you post an example code that triggers that error?
I don't have the whole lib in my head, it's easier to start with an example.

**Comment by mrkcmo** [comment]
I have changed the code already to just use the subprocess library for the push portion of my code.  Let me outline what I was trying to do so that perhaps you can give me some insight on how to move forward. 

Step 1: change branch back to master (working)
Step 2: Create new branch and checkout this new branch (working)
Step 3: Push new branch to server (this is where things break) 

I have tried using the Remote.push function and can't seem to get it to work. I lookup the ref for the new branch. Try and use that ref with the Remote.push and that is where I get all the issues. If you have some sample code on you do pushes I am happy to try again.

Thanks!
