### ISSUE TITLE
FFI error when recompiling libgit2 

### ISSUE THREAD

**Issue by eiselekd** [libgit2/pygit2#914]
I have recompiled and installed libgit2 v0.28 , I then also installed pygit2 via 
```python3 setup.py install --user``` . However I get some FFI error when starting 
clone_repository():

```
>>> from pygit2 import clone_repository
>>> repo_url = 'git://github.com/libgit2/pygit2.git'
>>> repo_path = '/tmp/test3'
>>> repo = clone_repository(repo_url, repo_path)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/d/.local/lib/python3.7/site-packages/pygit2-0.28.2-py3.7-linux-x86_64.egg/pygit2/__init__.py", line 222, in clone_repository
    opts = ffi.new('git_clone_options *')
ffi.error: struct git_remote_callbacks: wrong total size (cdef says 104, but C compiler says 112). fix it or use "...;" in the cdef for struct git_remote_callbacks to make it flexible
```
The error happens in:

```pygit2/__init__.py``` : clone_repository
```
    ...                                                                                                                                                           
    opts = ffi.new('git_clone_options *')                                                                                                                      
    crepo = ffi.new('git_repository **')                                                                                                                       
    ...                                                          
```                                                                                                 
There seem to be some struct size mismatch. It seems that the size of a structure has changed, however I dont understand what is actually checked. Does the cdef line mean that FFI is parsing git2.h and calculates a different struct size? 

I saw there is a ```pygit2/decl``` with c headers. Maybe this folder need to be updated?

**Comment by eiselekd** [comment]
I guess there is no easy way to support 2 version in parallel. Close issue...
```
v0.28 struct change

2 files changed, 3 insertions(+)
pygit2/decl/remote.h    | 1 +
pygit2/decl/transport.h | 2 ++

modified   pygit2/decl/remote.h
@@ -38,6 +38,7 @@ struct git_remote_callbacks {
 	git_push_negotiation push_negotiation;
 	git_transport_cb transport;
 	void *payload;
+	git_url_resolve_cb resolve_url;
 };
 
 typedef struct {
modified   pygit2/decl/transport.h
@@ -36,6 +36,8 @@ typedef int (*git_cred_acquire_cb)(
 	void *payload);
 
 typedef int (*git_transport_cb)(git_transport **out, git_remote *owner, void *param);
+typedef int (*git_url_resolve_cb)(git_buf *url_resolved, const char *url, int direction, void *payload);
+
 int git_cred_username_new(git_cred **cred, const char *username);
 int git_cred_userpass_plaintext_new(
 	git_cred **out,

```
